ALTER TABLE "Client"
  ALTER COLUMN "creditBalance" TYPE DOUBLE PRECISION USING "creditBalance"::DOUBLE PRECISION,
  ALTER COLUMN "creditBalance" SET DEFAULT 0.0;

ALTER TABLE "CreditLedger"
  ALTER COLUMN "amount" TYPE DOUBLE PRECISION USING "amount"::DOUBLE PRECISION,
  ALTER COLUMN "balanceAfter" TYPE DOUBLE PRECISION USING "balanceAfter"::DOUBLE PRECISION;
