ALTER TABLE IF EXISTS "MedicalItemPriceCache"
  ADD COLUMN IF NOT EXISTS "fixPrice" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "hetPrice" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "maxReferencePrice" DOUBLE PRECISION;
